name: Sync to Gitee

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Sync to Gitee
      # 换用专门针对 Gitee 优化的同步插件
      uses: Yikun/gitee-bucket-action@v1.4
      with:
        # 负责连接 GitHub 侧的临时凭证
        gitee-password: ${{ secrets.GITEE_TOKEN }}
        gitee-username: ${{ secrets.GITEE_USERNAME }}
        # 对应 GitHub 的账号名/仓库名
        git-username: rainkaze
        git-repo: SmartDictate
